title: 'Effective Flutter'
summary: |
  よくある誤用・その改善例など、実際にプロダクションアプリを組む際に必要な実践的な内容を詰め込んだFlutterの書籍です。

topics: [Flutter, Dart]
published: false
price: 500
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
